<?php
$this->headLink()
    ->prependStylesheet('https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css')
    ->prependStylesheet('https://maxcdn.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.min.css');

$this->inlineScript()
    ->prependFile('https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js')
    ->prependFile('https://code.jquery.com/jquery-2.1.4.min.js');
?>
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <?php echo $this->headTitle()->setSeparator(' - ')->setAutoEscape(false) ?>
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <?php echo $this->headMeta(); ?>
    <?php echo $this->headLink(); ?>
    <style>
        body { padding-top: 2.5em; }
        .service { display: flex; height: 100vh; flex-direction: column; }
        .service-header { flex-shrink: 0; }
        .service-content { flex: 1 0 auto; }
        .service-footer { flex-shrink: 0; padding-top: 2em; padding-bottom: 1em; }
        table.parameter-input label { font-weight:normal; }
    </style>
</head>
<body id="page-body-top" class="service">

<div class="service-content">
    <main class="container">
        <?php echo $this->content ?>
    </main>
</div>

<footer class="service-footer">
    <div class="container">
        <?php
        $className = $this->placeholder('classname');
        $fileName = $this->placeholder('filename');
        if ( $className <> '' && $fileName <> '' ) :
            ?>
            <table class="table">
                <tr>
                    <td>Class</td>
                    <td><code><?php echo $this->escapeHtml($className); ?></code></td>
                </tr>
                <tr>
                    <td>File</td>
                    <td><code><?php echo $this->escapeHtml($fileName); ?></code></td>
                </tr>
            </table>
        <?php endif; ?>
    </div>
</footer>

<?php echo $this->inlineScript(); ?>
</body>
</html>
